### ISSUE TITLE
Invalid URL format

### ISSUE THREAD

**Issue by jonybravo30** [layeh/piepan#21]
!add https://www.youtube.com/watch?v=MoLFza3lHmc

Invalid URL format. Either you did not provide a YouTube URL, or an error occurred during the downloading & encoding process.

**Comment by bontibon** [comment]
This does not appear to be an issue with piepan itself. Can you be a little more descriptive in your problem?

**Comment by matthieugrieger** [comment]
@bontibon: This is something from MumbleDJ, not quite sure why it is being reported here. It is also a very old version of MumbleDJ, as the newer versions use gumble instead of piepan.

@jonybravo30: This isn't an issue with piepan. Try updating to the latest release of MumbleDJ and you shouldn't have this problem.

**Comment by jonybravo30** [comment]
great thanks both!!
