### ISSUE TITLE
Convert p12 to pem certificate

### ISSUE THREAD

**Issue by Doidel** [layeh/piepan#25]
Hello again

I saw in another issue that you should convert your personal mumble certificate from p12 to pem. I tried that in several different ways but ended up with either corrupt certificate or ```x509: certificate signed by unknown authority```. Would you mind giving a hint on how to properly work with such a mumble certificate..?

Thanks very much, kind regards
Doidel

**Comment by matthieugrieger** [comment]
I'm not the dev, but I have some experience with Mumble certificates. I believe you're getting the `x509: certificate signed by unknown authority` error because you are using a self-signed certificate. You have to have your certificate signed by a [certificate authority](http://en.wikipedia.org/wiki/Certificate_authority). Alternatively you could use the `-insecure` flag to skip certificate checking.

By the way, here is how I converted by certs from p12 to pem:
```
openssl pkcs12 -in path.p12 -out newfile.crt.pem -clcerts -nokeys
openssl pkcs12 -in path.p12 -out newfile.key.pem -nocerts -nodes
```

**Comment by Doidel** [comment]
Thousand thanks man, all scripts running!!!
