### ISSUE TITLE
SetMute seems to not do anything

### ISSUE THREAD

**Issue by Doidel** [layeh/piepan#27]
Hi

My bot can't unmute myself (using ```piepan.Self.SetMute```). My bot is on a server where you can't mute yourself (so when I use ```SetMute(true)``` then I get a proper ```permissionDenied```), however you're allowed to unmute yourself. So I'm trying to do the same I do with clicking: I (as a normal user) move to a channel where I'm muted per default. I rightclick on me and take the flag away at "muted".
When I try this as the bot (move to channel, ```SetMute(false)```) then nothing happens at all. No permission denied, no error, no action.
Do you happen to have an idea what I'm doing wrong?

All the best
Doidel

**Comment by bontibon** [comment]
The reason why `SetMuted` was not working was because the user was "suppressed" and not "muted", which the server considers two separate things.

I have pushed an update to gumble (layeh/gumble@71e6139bb9f420bc0a95f354f8838788ccc385cd) which adds [`User.SetSuppressed`](https://godoc.org/github.com/layeh/gumble/gumble#User.SetSuppressed). You should update gumble (`go get -u github.com/layeh/gumble/gumble`) and rebuild piepan to have access to the new method.

**Comment by Doidel** [comment]
Awesome, works like a charm, thank you!
I tried to find a place where I can donate something to the project, but was unable to find something. Is there any possibility..? :)

**Comment by bontibon** [comment]
Thank you, @Doidel, I appreciate that! I have just added a donation button to [layeh.com](http://layeh.com/).
